Update code samples in 5.x docs to use const
expressjs/expressjs.com pull request #1057
Opened 2019-07-19 22:00 UTC by RamirezAlex

This update the code samples in 5.x alpha documentation to use the modern keyword `const` instead of `var`

Please review @crandmck @dougwilson :)

2019-09-05 23:19 UTC, crandmck commented
Seems reasonable to me.  
@dougwilson @wesleytodd Do you have an opinion?

2019-09-05 23:29 UTC, dougwilson requested changes
I'm fine with it, though found at least one issue. There is a lot to go through, so I may have missed something. I'm not sure if this was just done with only as find and replace, or the examples were all tested to validate they are working or not still after the changes.

2019-09-05 23:29 UTC, dougwilson commented on _includes/api/en/5x/app-listen.md
> +  const server = http.createServer(this)
This is meant to be the exact code that is in the Express source tree: https://github.com/expressjs/express/blob/5f0c829d7ca7da746ee859f13a54631000f8a9b5/lib/application.js#L602-L605

2019-09-06 21:00 UTC, wesleytodd approved these changes
Other than @dougwilson's comment, LGTM!

2019-10-28 17:04 UTC, crandmck commented
Since he made Doug's suggested change, I'm going to merge.
@RamirezAlex sorry for the delay.

2019-10-28 17:04 UTC, merged