Update req-secure header and excerpt
expressjs/expressjs.com pull request #1094
Opened 2020-01-12 11:45 UTC by markjszy

Based on behavior of current site, it looks like req-secure ought to have the header reinstated. Also, es-lint fails with the JS block-style example for a few reasons, most importantly the "unused expression". For this example, I opted to just have a single line instead of the block-style code, which I am not sure could be made acceptable to es-lint without a less attractive option like introducing a variable (e.g. assign the result of the expression to isSecure...)

2020-01-20 17:43 UTC, jonchurch requested changes

2020-01-20 17:43 UTC, jonchurch commented on _includes/api/en/5x/req-secure.md
You can disable the particular eslint rule that's complaining with `<!-- eslint-disable no-unused-vars -->` before the offending line. That way the code will still be linted, but we can ignore that particular rule for this code block. 

With an inline code example, the linter will never check it.

2020-01-20 17:44 UTC, jonchurch commented
Thank you for the contribution! ❤️ 

**Note to others: this PR aims to fix one of the two issues that's causing CI to fail**

2020-01-20 17:52 UTC, jonchurch commented on _includes/api/en/5x/req-secure.md
> + A Boolean property that is true if a TLS connection is established. Equivalent to `req.protocol === 'https'`.
```suggestion
 A Boolean property that is true if a TLS connection is established. Equivalent to:
 
 <!-- eslint-disable no-unused-expressions -->
 ```js
req.protocol === 'https'
```

```

2020-01-20 19:55 UTC, jonchurch requested changes

2020-01-20 19:55 UTC, jonchurch commented on _includes/api/en/5x/req-secure.md
> +<!-- eslint-disable no-unused-expressions -->
Apologies, I should have been more specific. The eslint comment needs to be just above the code block, the linter is choking on finding HTML in the js code block.

Thank you for the quick change, btw!

2020-01-20 23:10 UTC, jonchurch approved these changes
LGTM 👍

2020-01-23 01:51 UTC, jonchurch commented
@expressjs/expressjs-com This PR will fix the currently failing CI

2020-01-28 19:36 UTC, wesleytodd commented
@markjszy, If you have time can you rebase and squash this to a single commit?  If you do that we can just merge here in the UI.  Otherwise I should be able to merge this next weekend when I have time.

2020-02-05 06:51 UTC, anton-marchenko commented
> @markjszy, If you have time can you rebase and squash this to a single commit? If you do that we can just merge here in the UI. Otherwise I should be able to merge this next weekend when I have time.

Hi. I have a time for squashing this commits in single one. But it needs to open another PR as I understand. Can I do that? Or it is better waiting for your actions?

2020-02-05 15:51 UTC, markjszy commented
Hi @anton-marchenko @wesleytodd @jonchurch  sorry to take a little while to follow up about this. I can attempt to revise this PR as requested (squash commits) tonight if that is OK. I'll write in again if there's some issue I run into or don't expect to be able to do that soon.

2020-02-09 20:24 UTC, anton-marchenko commented
> Hi @anton-marchenko @wesleytodd @jonchurch sorry to take a little while to follow up about this. I can attempt to revise this PR as requested (squash commits) tonight if that is OK. I'll write in again if there's some issue I run into or don't expect to be able to do that soon.
> 
> **Update** : I attempted to squash and clean up, but am afraid I did not do this correctly. Open to any help or guidance as to how to do this properly, or else am happy to rely on someone else to do it instead. Sorry again for the delay!

Hi. I just created quick workaround for this situation. Please, approve it: https://github.com/expressjs/expressjs.com/pull/1107

2020-02-24 07:40 UTC, merged