docs: document http-terminator (fixes #1096)
expressjs/expressjs.com pull request #1097
Opened 2020-01-20 03:12 UTC by gajus

2020-01-20 17:22 UTC, jonchurch approved these changes
Edit: I've requested one change, but otherwise...
LGTM 👍 
This package actually looks quite good too btw, kudos! 

~~P.S. the failing CI doesn't have anything to do with this PR.~~

The CI was failing before this PR, but there is one styling error introduced by it, which I suggested a change on. ❤️

2020-01-20 17:48 UTC, jonchurch requested changes

2020-01-20 17:48 UTC, jonchurch commented on en/advanced/healthcheck-graceful-shutdown.md
> +  httpTerminator.terminate();
```suggestion
  httpTerminator.terminate()
```
Actually this one extra semicolon is throwing an error in the CI for code styling

2020-01-21 17:08 UTC, jonchurch approved these changes
Thanks! LGTM

2020-01-27 04:10 UTC, gajus commented
Do I need to do anything regarding the failing tests?

2020-01-27 16:30 UTC, jonchurch commented
@gajus Nope, that's not a blocker and there's a PR #1094 open that will fix the failing CI. 

This is pending review from @expressjs/expressjs-com and after that it will likely get merged in.

2020-02-15 07:07 UTC, wesleytodd commented
This is not a judgement on the package, but I would like to see the express documentation have less documentation on third party packages.  Today there is a ton of outdated stuff which was added years ago, and I would like to not make it any worse.  I think we should consider moving stuff like this into an "awesome list" format instead of it being on the express website.  Thoughts about this direction @jonchurch?

2020-02-15 14:08 UTC, gajus commented
> I think we should consider moving stuff like this into an "awesome list" format instead of it being on the express website.

What makes that different from the current format?

2020-02-15 23:43 UTC, wesleytodd commented
We wouldn't maintain it :)  The problem with it on the website is it makes us already limited maintainers have more work.  In an awesome list I, and I am guessing the other primary maintainers would not maintain it.

2020-02-16 02:34 UTC, jonchurch commented
I think having a discussion about cleaning up the site would be fruitful. IMO the site should document the project and not much else. 

However, as things stand we do have these kind of sections and I think OP’s library is high quality so Im pro merging. 

These kinds of sections (recommendations of libraries) can always be removed in the future, and I think it would be pragmatic to move towards that.

2020-04-03 04:02 UTC, dougwilson approved these changes
I know there was a bunch of conversation in this PR revolved around the greater idea on 3-rd party modules, but they are there today, and this one is really nice, so I'm going to merge it in and if there is ever a policy in the future, it's easy to adjust the contents at that time 👍

2020-04-03 04:02 UTC, merged

2020-04-03 04:45 UTC, gajus commented
Thank you!