doc: document `next('router')` behaviour
expressjs/expressjs.com pull request #1131
Opened 2020-04-03 13:44 UTC by HarshithaKP

Refs: https://github.com/expressjs/expressjs.com/issues/1126

2020-04-17 07:42 UTC, dougwilson requested changes
Thanks! I think we need to get some actual documentation around this feature, though. An example is always good for visual learners, but we should be providing a descriptive section regarding the feature, how it works, etc. and then we can following it with the example you made 👍

2020-04-17 09:51 UTC, HarshithaKP commented
@dougwilson, thanks. Described about `next('router')` feature followed by example. PTAL.

2020-04-22 23:47 UTC, dougwilson commented
Thank you!

2020-04-22 23:47 UTC, dougwilson commented on _includes/api/en/5x/router-METHOD.md
> +the name of a router will cause all the remaining route callbacks on that router
```suggestion
the string `'router'` will cause all the remaining route callbacks on that router
```

2020-04-23 00:12 UTC, HarshithaKP commented on _includes/api/en/5x/router-METHOD.md
> +the name of a router will cause all the remaining route callbacks on that router
@dougwilson, fixed it. PTAL.

2020-04-23 00:24 UTC, gireeshpunathil approved these changes

2020-04-23 00:34 UTC, dougwilson approved these changes

2020-04-23 00:37 UTC, merged

2020-04-23 00:37 UTC, dougwilson commented
squashed & merged