Update 4x and 5x docs to include `router(req, res, next)` documentation
expressjs/expressjs.com pull request #1152
Opened 2020-05-15 23:33 UTC by SimplyComplexable

API docs currently provide an example of using the `Router.router()` instance imperatively
as a middleware, but it isn't immediately clear that this can be used as a regular function
within a handler by explicitly passing in the arguments.

Resolves
#1151

2020-05-16 00:03 UTC, dougwilson requested changes
Thank you so much! It looks like the CI is noting that `npm test` does not pass, from a linting issue. The code blocks should be StandardJS formatted is all.

2020-05-16 00:05 UTC, dougwilson commented
Thanks so much! there is the formatting noted above, but also we probably also want to add some API docs itself, and examples can always be used in addition to API docs. An API doc would be a section about the specific API in question (`router(req, res, next)`) and a description about what it is and what it does. Then you can (optionally) follow up with an example of it in use.

2020-05-18 15:23 UTC, SimplyComplexable commented
@dougwilson to clarify, are you just saying to add a separate file in the same area (i.e. router-function) in the same area folders? Or is there a different area that your suggesting this be added to?

2020-05-18 16:47 UTC, dougwilson commented
I will need to take a look if you are looking for that level of detailed instructions. But maybe this will help: each API in express has a section that has a header listing the API, a description about the API, and optionally an example of it's usage. That is what we need for router(req, res, next) API.

2020-05-21 16:03 UTC, dougwilson requested changes
An API doc would be a section about the specific API in question (`router(req, res, next)`) and a description about what it is and what it does. Then you can (optionally) follow up with an example of it in use.

These changes are adding an example to the `Router` constructor that is unrelated to that API. A new API section needs to be created with a header of the API (`router(req, res, next)`), a description about what it is and what it does, then optionally add an example to that section about said API.

2020-05-22 15:16 UTC, SimplyComplexable commented
Thanks @dougwilson, I'll be working on this today.

2020-06-05 23:19 UTC, SimplyComplexable commented
@dougwilson I added a dedicated page for this. I think this is what you were going for. Let me know if there's anything else.

2020-06-18 17:39 UTC, SimplyComplexable commented
@dougwilson any update on this?

2020-07-31 07:38 UTC, crandmck commented
Sorry I haven't been around to comment on this earlier @SimplyComplexable ...

Unfortunately, since this applies to applies to 5.x as well as 4.x, here we are seeing the cost of publishing the 5x API docs.  We have to do some manual duplication. Not end of the world, but :-( 

Anyway, just a few things that need to be done:
- Update `_includes/api/en/5x/menu.md` in the same way as `4x/menu.md` so the new heading is in the navigation.
- Add `_includes/api/en/5x/router-instance.md` that duplicates `_includes/api/en/5x/router-instance.md`

Other comments inline.  It's getting there, .... I think it's a good addition; based on what @dougwilson said in https://github.com/expressjs/expressjs.com/issues/1151, it sounds like it's omission/doc-bug.

2020-07-31 08:35 UTC, crandmck requested changes

2020-07-31 08:35 UTC, crandmck commented on _includes/api/en/4x/menu.md
> +            <li><a href="#router.instance">router(req, res, next)</a>
None of the other headings in the API ref include the arguments, but rather they just have the `()` even when the method takes args.  That's just a convention, but I think we should follow it. So it would just be `router()`.

2020-07-31 08:35 UTC, crandmck commented on _includes/api/en/4x/router-instance.md
> +<h3 id='router.instance'>router(req, res, next)</h3>
If title changes, need to change here, too.

2020-07-31 08:35 UTC, crandmck commented on _includes/api/en/4x/router-instance.md
> +you can use in a few different ways.
Pls reword (combines passive voice & 2nd person).  Suggest:
"Once you create a router instance and add all relevant route handlers, you can use it in a few different ways.

2020-07-31 08:35 UTC, crandmck commented on _includes/api/en/4x/router-instance.md
> +  - Directly pass it to another router's route handler.
Do not use a bullet here (bullets are for list items).

I think it's technically correct, but calling `app` in example below a "router" is potentially confusing, since it's referred to elsewhere as an `app` object, not a `Router` object.

Suggest:
`Directly pass it to a method of a route handler object, such as the [app](#app) object, as shown here:`

2020-07-31 08:35 UTC, crandmck commented on _includes/api/en/4x/router-instance.md
> +  - Or you can call pass the `req`, `res`, and `next` arguments to the `Router` instance as a function
Do not use a bullet here (bullets are for list items).

Also "...can call pass..." --> "... can pass ..."

2020-07-31 08:35 UTC, crandmck commented on _includes/api/en/4x/router-instance.md
> +  within another router's route handler.
This wording is very confusing to me...  It says
"...passing req, res, and next arguments to the `Router` instance as a function....",  but AFAICT the function is being passed to an `app` instance, not a `Router` instance.  

Maybe try rewording into multiple sentences ..?

2020-07-31 08:35 UTC, crandmck commented on _includes/api/en/4x/router-instance.md
> +This allows you to have a more fine-grained control over what the router instance is responsible for,
Consider moving the explanation above the code example.  People sometimes overlook it when it comes after, and can help sometimes to understand the code if you read the text first.  This is just a suggestion.

2021-12-16 20:28 UTC, dougwilson commented
I'm going to close this due to no follow ups to the suggestions above in a while. If you would like to pick this up again, just re-open a new PR 👍

2021-12-16 20:28 UTC, closed without merging