res.send documentation change
expressjs/expressjs.com pull request #1179
Opened 2020-07-20 20:12 UTC by schamberg97

This documentation is incorrect, because res.send also accepts booleans. Example could be even found in express tests: 
```js
it('should return true when the resource is not modified', function(done){
      var app = express();
      var etag = '"12345"';

      app.use(function(req, res){
        res.set('ETag', etag);
        res.send(req.fresh); // <-- req.fresh returns Boolean
      });

      request(app)
      .get('/')
      .set('If-None-Match', etag)
      .expect(304, done);
    })
```

2020-07-24 05:12 UTC, gireeshpunathil commented
LGTM

FWIW, a more compact test:

```js
require('express')().get('/', (q, r) => {
  r.send(new Boolean(true))
}).listen(12000, () => {
  require('http').get('http://localhost:12000', (m) => {
    m.on('data', (d) => console.log(d.toString()))
  })
})
```
outputs `true`.

2020-07-24 08:16 UTC, schamberg97 commented
@gireeshpunathil True, just wanted to point out that even the tests depend on this feature, but it’s not even documented

2020-07-27 03:20 UTC, dougwilson requested changes
Can you also update the 5x documentation as well?

2020-07-27 13:20 UTC, schamberg97 commented
Umm, sure, I’ll do it in a couple of hours, when I get to my computer

2020-07-28 00:43 UTC, dougwilson commented
no rush @schamberg97 . just ping us when updated 👍

2020-07-29 14:38 UTC, schamberg97 commented
> no rush @schamberg97 . just ping us when updated 👍

@dougwilson Done 👍

2020-08-05 05:31 UTC, dougwilson approved these changes

2020-08-05 05:32 UTC, crandmck commented
This looks ready to land @dougwilson ... but I won't take that liberty since I'm late to the party here.

2020-08-16 19:37 UTC, crandmck commented
OK, since Doug approved this straightforward change, and no one has objected, I'm going to go ahead and land it.

2020-08-16 19:37 UTC, merged