Mention both 'route' and 'router' options for next()
expressjs/expressjs.com pull request #1211
Opened 2020-10-02 08:02 UTC by jorenvandeweyer

Mention both options to skip or jump out of a route / router with the `next` function.

2020-10-02 12:45 UTC, rodion-arr approved these changes
LGTM

2021-01-13 02:08 UTC, dougwilson requested changes

2021-01-13 02:08 UTC, dougwilson commented on _includes/api/en/4x/routing-args.html
> +current router. You can use this mechanism to impose pre-conditions
This next sentence needs to be updated now that `'router'` is included in the previous sentence, as it goes on only to explain `'route'` but not `'router'`.

2021-12-16 20:30 UTC, dougwilson commented
I'm going to close this due to no follow ups to the suggestions above in a while. If you would like to pick this up again, just re-open a new PR 👍

2021-12-16 20:30 UTC, closed without merging