Update Neo4j connection example to neo4j-driver
expressjs/expressjs.com pull request #1261
Opened 2021-05-14 13:47 UTC by adam-cowley

The updated example uses the officially supported [Neo4j JavaScript Driver](https://github.com/neo4j/neo4j-javascript-driver).

2021-05-14 20:48 UTC, rodion-arr approved these changes

2021-05-15 04:45 UTC, dougwilson requested changes

2021-05-15 04:45 UTC, dougwilson commented on en/guide/database-integration.md
> +**Module**: [neo4j-javascript-driver](https://github.com/neo4j/neo4j-javascript-driver)
```suggestion
**Module**: [neo4j-driver](https://github.com/neo4j/neo4j-javascript-driver)
```

It looks like the name of the module is just neo4j-driver.

2021-05-15 04:45 UTC, dougwilson commented on en/guide/database-integration.md
> +      console.log(res.records[0].get('count')
```suggestion
      console.log(res.records[0].get('count'))
```

Missing closing parans

2021-05-27 13:24 UTC, iamarpitpatidar approved these changes

2021-05-31 03:36 UTC, dougwilson approved these changes

2021-05-31 03:37 UTC, merged