updated URL for diference in templating engines
expressjs/expressjs.com pull request #1294
Opened 2021-11-20 05:28 UTC by wizzenalum

#1290 mention that URL not working so changed the URL provided to read the differences between template engines. because that no longer working.
before
```
See also [Comparing JavaScript Templating Engines: Jade, Mustache, Dust and More](https://strongloop.com/strongblog/compare-javascript-templates-jade-mustache-dust/).
```
after
```
See also [Comparing JavaScript Templating Engines: Jade, Mustache, Dust and More](https://medium.com/@jack.yin/comparing-javascript-templating-engines-jade-mustache-dust-and-more-6a4469ac716a).
```

2021-11-22 19:41 UTC, dougwilson requested changes
This is awesome, thank you. Please go ahead and update the rest of the references to that blog.

2021-11-23 08:10 UTC, wizzenalum commented
hello can any one tell me, why this pull request is not commited

2021-11-23 17:10 UTC, aravindvnair99 commented
> hello can any one tell me, why this pull request is not commited

Hey @wizzenalum! There are pending changes as mentioned by @dougwilson at https://github.com/expressjs/expressjs.com/pull/1294#pullrequestreview-812949793

Could you please update the same in this PR itself?

2022-02-18 02:42 UTC, dougwilson commented
Closing due to no follow up and the strongloop blog has been fixed so the current links work again.

2022-02-18 02:42 UTC, closed without merging