Updated the Installation Docs
expressjs/expressjs.com pull request #1295
Opened 2021-11-21 09:08 UTC by nshah1729

Added a command for installing express as it's the most widely used command for installing Express(in all the tutorials I have seen till now! )
![Screenshot 2021-11-21 at 2 28 09 PM](https://user-images.githubusercontent.com/58332678/142756203-4890dd71-ea49-401f-bf3b-cdb3198bda9e.png)

2021-11-21 09:11 UTC, aravindvnair99 requested changes
@nshah1729 That's the same as line 37

2021-11-21 11:09 UTC, nshah1729 commented
@aravindvnair99 Isn't ```npm install express  --save``` deprecated?
After npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed

2021-11-21 14:47 UTC, aravindvnair99 commented
> @aravindvnair99 Isn't `npm install express --save` deprecated? After npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed

@nshah1729 That is correct. I would be more in favour for that change as opposed to the currently proposed changes.

2021-11-21 15:14 UTC, nshah1729 commented
@aravindvnair99 So what should I do? 
Should I close this PR and create another PR with ```npm install express --save``` removed??

2021-11-21 15:45 UTC, aravindvnair99 commented
> @aravindvnair99 So what should I do? Should I close this PR and create another PR with `npm install express --save` removed and replace it with `npm i express`??

@nshah1729 You can edit in same PR itself. Any changes you make in same branch would be reflected here.

As for what to do, my suggestion would be to replace with `--save`.

Note: There are others in the community as well who might have a different opinion. You could either wait for others to pitch in or make the change and wait for others to pitch in. @dougwilson finalises.

2021-11-21 15:53 UTC, nshah1729 commented
ok Sure!

2021-11-21 15:55 UTC, nshah1729 commented
I've done!Please check

2021-11-21 16:05 UTC, rodion-arr commented
I think this question was raised before and it was decided to leave --save. See https://github.com/expressjs/expressjs.com/pull/936

2021-11-21 18:33 UTC, dougwilson commented
With rhe number of times folks keep trying to PR this same change, if merging this will take the PRs stop, then that is probably for the better. There is the note below this that explains the `--save` option and this PR doesn't remove it, so hopefully thay is satisfactory for the readers.

2021-11-21 19:17 UTC, aravindvnair99 approved these changes
As per the official statistics, most downloads are for npm 8, 7, 6 and comparatively much lesser for 1, 2, 3, 4 and 5.  Hence, I'm in favour of this PR especially since this is a starter guide and the chance of someone starting off with an older version of Node.js or npm is unlikely also considering the fact that Node.js 8 and above ships with npm 6+ even though Node.js 12 and 14 are in maintenance now with Node.js 16 being the active LTS.

References:

- npm download stats per version: https://www.npmjs.com/package/npm?activeTab=versions
- npm version shipped with Node.js: https://nodejs.org/en/download/releases/
- Node.js LTS status and release cycle: https://github.com/nodejs/Release#release-schedule

TLDR: I'm in favour of this PR

2021-11-21 19:27 UTC, dougwilson commented
Sounds good to me. @nshah1729 can you update this command in the starter guides for the other languages, pease?

2021-11-22 04:08 UTC, nshah1729 commented
@dougwilson Sure! Please merge this PR...I will update the same create PRs in other langs also!

2021-11-22 04:10 UTC, dougwilson commented
Just push the updates to the branch this PR is made from and they will be added automatically 👍 no need to make a bunch of PRs if you don't want to. As for merging this PR, either get all the updates added to this PR or get all the PRs made and then we can merge.

2021-11-22 04:10 UTC, dougwilson requested changes
Ensure command is consistent across all languages.

2021-11-22 20:02 UTC, aravindvnair99 requested changes
We should  be using `console` instead of `sh` as the former is for terminal interfaces and latter is for shell scripts. Difference:

`sh` / `shell` / `bash`:
```sh
npm i express
```

`console` / `terminal`:

```console
npm i express
```

2021-11-22 20:02 UTC, aravindvnair99 commented on en/starter/installing.md
>  ```sh
```suggestion
```console
```

2021-11-22 20:02 UTC, aravindvnair99 commented on ja/starter/installing.md
>  ```sh
```suggestion
```console
```

2021-11-22 20:02 UTC, aravindvnair99 commented on th/starter/installing.md
>  ```sh
```suggestion
```console
```

2021-11-22 20:02 UTC, aravindvnair99 commented on tr/starter/installing.md
>  ```sh
```suggestion
```console
```

2021-11-22 20:02 UTC, aravindvnair99 commented on zh-cn/starter/installing.md
>  <code class="language-sh" translate="no">
```suggestion
```console
```

2021-11-22 20:02 UTC, aravindvnair99 commented on zh-cn/starter/installing.md
>  </pre>
```suggestion
```
```

2021-11-22 20:04 UTC, dougwilson commented
Oh neat, I never knew that there was even a console/terminal specifier. Did you verify the jekyll pipeline understands it?

2021-11-22 20:28 UTC, aravindvnair99 commented
> Oh neat, I never knew that there was even a console/terminal specifier. Did you verify the jekyll pipeline understands it?

@dougwilson Yep, Kramdown supports it. GFM is entirely supported.

Reference:

- https://github.com/expressjs/expressjs.com#formatting
- https://github.com/kramdown/parser-gfm
- https://kramdown.gettalong.org/quickref.html#code-blocks

2021-11-25 05:55 UTC, aravindvnair99 commented
Hey @nshah1729! Any updates?

2021-11-25 07:08 UTC, nshah1729 commented
@aravindvnair99 I've committed the changes. Is it done?

2021-11-25 07:37 UTC, aravindvnair99 commented on th/starter/installing.md
>  ```sh
@nshah1729 you missed this one

2021-11-25 11:41 UTC, aravindvnair99 commented
> @aravindvnair99 I've committed the changes. Is it done?

@nshah1729 https://github.com/expressjs/expressjs.com/pull/1295#discussion_r754592877

2021-11-25 11:52 UTC, nshah1729 commented on th/starter/installing.md
>  ```sh
Sorry!

2021-11-25 12:07 UTC, aravindvnair99 requested changes

2021-11-25 12:07 UTC, aravindvnair99 commented on zh-cn/starter/installing.md
> +$ npm install express
@nshah1729 Can you add `` ``` `` after line 42 here on the next line to close the console formatting? Do leave a blank line before the next heading.

2021-11-27 18:38 UTC, aravindvnair99 requested changes
@nshah1729 Can you bring over changes from #1304, #1308 and the remaining ones into this PR?

2021-11-28 13:40 UTC, nshah1729 commented
@aravindvnair99 You mean to say that I remove --> ```默认情况下，版本为 npm 5.0+ 的 npm install 将模块添加到 `package.json` 文件中的 `dependencies` 列表；对于较早版本的 npm，必须显式指定 `--save` 选项。 今后运行 `app` 目录中的 `npm install` 将自动安装依赖项列表中的模块。``` from the current **PR** (***the last para***)?

2022-02-18 03:28 UTC, dougwilson approved these changes

2022-02-18 03:31 UTC, merged