Fix incorrect link in companies using express
expressjs/expressjs.com pull request #1335
Opened 2022-04-12 02:14 UTC by BLooDBRothER

## Incorrect link is found in [this](https://expressjs.com/en/resources/companies-using-express.html) page.

The link for Agrippa present on the page (https://agrippa.no/en) gives a page not found, which could be changed to https://agrippa.no.

## Screenshot for the reference.
![express_companies_incorrect](https://user-images.githubusercontent.com/63643748/162865350-d8c30c70-1afc-4879-8376-beda2c9a9945.png)
![express_companies_correct](https://user-images.githubusercontent.com/63643748/162865360-8954481b-2711-480d-8a57-9544e1d072b6.png)

2022-04-14 22:26 UTC, daniel7byte approved these changes

2022-04-16 21:40 UTC, import-brain approved these changes

2022-04-17 02:16 UTC, aravindvnair99 requested changes
@BLooDBRothER Thank you for your contribution! Please change HTTP to HTTPS as well.

2022-04-17 02:16 UTC, aravindvnair99 commented on en/resources/companies-using-express.md
> +    <a target="_new" class="imagelink" href="http://www.agrippa.no">
```suggestion
    <a target="_new" class="imagelink" href="https://www.agrippa.no">
```

2022-04-17 12:10 UTC, BLooDBRothER commented
@aravindvnair99 I didn't see it :blush:. Commited the change.

2022-04-17 14:47 UTC, aravindvnair99 requested changes
@BLooDBRothER One last change... `www` can also be removed since it's redirecting to naked domain anyways.

2022-04-17 14:47 UTC, aravindvnair99 commented on en/resources/companies-using-express.md
> +    <a target="_new" class="imagelink" href="https://www.agrippa.no">
```suggestion
    <a target="_new" class="imagelink" href="https://agrippa.no">
```

2022-04-17 15:42 UTC, BLooDBRothER commented
@aravindvnair99 commited the change.

2022-04-17 15:43 UTC, aravindvnair99 approved these changes

2022-04-20 21:06 UTC, dougwilson approved these changes

2022-04-20 21:07 UTC, closed without merging