Remove ancillary pages and corresponding menu nav items
expressjs/expressjs.com pull request #1484
Opened 2024-04-11 04:11 UTC by crandmck

Per discussion in TC and:
- https://github.com/expressjs/discussions/issues/211
- https://github.com/expressjs/discussions/issues/105

Details are laid out in https://github.com/expressjs/expressjs.com/wiki/Discuss:-Remove-pages-from-docs.

Not previously discussed: The home page has a "Frameworks" tile with a link to one of the pages being removed.
For the English page, I replaced this with a link to middleware.  For non-en pages, I removed the text with no replacement.

2024-04-11 14:11 UTC, wesleytodd approved these changes

2024-04-11 19:12 UTC, jonchurch requested changes
Read through the english removals. We are nuking some whole pages, but also removing references to those pages from other content, which is why the diff is as large as it is.

I left a suggestion for wording, LGTM either way though

2024-04-11 19:12 UTC, jonchurch commented on index.md
> +      functionality is contained in Express <a href="{{ page.lang }}/resources/middleware.html">middleware</a> modules.
```suggestion
      Express is a lightweight and flexible routing framework that provides a minimal core feature set.
      Its capabilities are designed to be augmented through the use of Express <a href="{{ page.lang }}/resources/middleware.html">middleware</a> modules.
```

What do you think about this? I'd rather we state "minimal feature set" vs "minimal functionality"

2024-04-12 04:17 UTC, crandmck commented on index.md
> +      functionality is contained in Express <a href="{{ page.lang }}/resources/middleware.html">middleware</a> modules.
Thanks @jonchurch I agree "minimal functionality" does seem rather negative.  

Your suggestion is good, but on reflection, I feel like we should be even more succinct, and just say something like 

```
Express is a routing framework with minimal functionality that is meant to be augmented through the use of ...
```

TBH, my original proposal was focussed on removing those pages with links to 3p sites, and I hadn't thought through the changes required to the home page.  But of course, it's of particular importance, so I appreciate your attention to the matter.

2024-04-13 16:33 UTC, jonchurch commented on index.md
> +      functionality is contained in Express <a href="{{ page.lang }}/resources/middleware.html">middleware</a> modules.
LGTM!

2024-04-13 16:36 UTC, jonchurch approved these changes

2024-04-15 10:18 UTC, UlisesGascon approved these changes

2024-04-17 01:03 UTC, merged