feat - adjust in layout and theme - v2
expressjs/expressjs.com pull request #1528
Opened 2024-06-20 12:19 UTC by carlosstenzel

Adjust in layout and theme

Before

https://github.com/expressjs/expressjs.com/assets/3890516/e123d4a2-294e-4998-9099-97c09bc592f4

After

https://github.com/expressjs/expressjs.com/assets/3890516/c600615f-05f7-46bb-a7fc-3a5d57d038eb

2024-06-23 19:02 UTC, chrisdel101 commented
Apologies for if anything appears overly critical, but there are alot of changes here so it just more room for critique :)

Overall there are some good ideas here, but maybe too many? I'd personally rather have had you just do a PR that was say "Reformat Nav Bar," since the nav is problematic,  rather than trying to tackle the entire site in one PR (and which I'm honestly not seeing a huge need for). If you are open to that, maybe we could just focus on the nav parts to start with? And try the rest in another PR?

Anyway, I did some reviewing of the whole thing, but due to the size I could not check every single thing. I'd strongly suggest we do another pass over this again later.

I made some comments. I put "personally" or "I think" in many of the comments since I don't see the need for them, but @crandmck might have a different outlook. 

The others probably do require the changes. Get rid of all the `important`s for sure. 

Random other things I'd suggest
- I miss the border around the nav bar dropdowns. You've removed this.
- On mobile view there is some strange x-scroll occurring on the API pages. This is not happening in production. Could just be my setup, but please check that out. 
- On a random page the text content stretches all the way to the edge of the page. We can't have this. I made comment about text block width conventions, or you can fall back to the current settings since they work okay.

![Screenshot 2024-06-23 at 12 50 32 PM](https://github.com/expressjs/expressjs.com/assets/14151974/95978d8f-1802-40dd-baa2-b0a3c85dd65c)

2024-06-24 13:07 UTC, carlosstenzel commented
> Apologies for if anything appears overly critical, but there are alot of changes here so it just more room for critique :)
> 
> Overall there are some good ideas here, but maybe too many? I'd personally rather have had you just do a PR that was say "Reformat Nav Bar," since the nav is problematic, rather than trying to tackle the entire site in one PR (and which I'm honestly not seeing a huge need for). If you are open to that, maybe we could just focus on the nav parts to start with? And try the rest in another PR?
> 
> Anyway, I did some reviewing of the whole thing, but due to the size I could not check every single thing. I'd strongly suggest we do another pass over this again later.
> 
> I made some comments. I put "personally" or "I think" in many of the comments since I don't see the need for them, but @crandmck might have a different outlook.
> 
> The others probably do require the changes. Get rid of all the `important`s for sure.
> 
> Random other things I'd suggest
> 
>     * I miss the border around the nav bar dropdowns. You've removed this.
> 
>     * On mobile view there is some strange x-scroll occurring on the API pages. This is not happening in production. Could just be my setup, but please check that out.
> 
>     * On a random page the text content stretches all the way to the edge of the page. We can't have this. I made comment about text block width conventions, or you can fall back to the current settings since they work okay.
> 
> 
> ![Screenshot 2024-06-23 at 12 50 32 PM](https://private-user-images.githubusercontent.com/14151974/342108923-95978d8f-1802-40dd-baa2-b0a3c85dd65c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzM5NDgsIm5iZiI6MTcxOTIzMzY0OCwicGF0aCI6Ii8xNDE1MTk3NC8zNDIxMDg5MjMtOTU5NzhkOGYtMTgwMi00MGRkLWJhYTItYjBhM2M4NWRkNjVjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEyNTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MjIxNzcyNDJjMzhlYjAxMzgzYzMyNTRjOTQ0MDFkNTRiNDAxZmQ0MGQzMzRhNWUyNzkwN2EzMDAxOWZiNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HLAYxSZKzul6SU74np3qo1mGKcQx0iJXMjQGwBV2-VE)

Thank you for the review, we can divide and treat each point separately.

I couldn't see your review comments, do I need permission?

2024-06-24 13:21 UTC, carlosstenzel commented
@chrisdel101 
I moved in another PR, this point about change icon in toggle theme
https://github.com/expressjs/expressjs.com/pull/1532

2024-06-24 14:04 UTC, chrisdel101 requested changes

2024-06-24 14:04 UTC, chrisdel101 commented on _includes/header/header-en.html
> +        <i class="fa fa-sun-o fa-lg hidden-light"></i>
Personally I don't like this icon b/c it looks like the "settings" gear icon to me. It's not clear that it means "light mode" immediately.

2024-06-24 14:04 UTC, chrisdel101 commented on _includes/header/header-en.html
> +      <input id="q" class="input-search" placeholder="Search ...">
I think the search bar should remain on the left side of the nav bar since moving it is a drastic-ish change. Also there's some overlap issues. Also happens on the Express Logo icon side too
![Screenshot 2024-06-23 at 11 55 55 AM](https://github.com/expressjs/expressjs.com/assets/14151974/fbd00066-07c0-4b22-8c3d-8f12afaaaf16)

2024-06-24 14:04 UTC, chrisdel101 commented on css/dark-theme.css
> +  background: #000;
- Why undo the variable with a hard-coded value? If you want a one-off change I suggest making it variable anyway. 

- And why change the color here anyway? I don't see the need for this.

2024-06-24 14:04 UTC, chrisdel101 commented on css/dark-theme.css
> +  color: #b6b6b6;
- Again, I don't see any reason to hardcode this. You should make it a variable. 
- I personally like the white color that is is now, but I could be sold on this color if others like it more.

2024-06-24 14:04 UTC, chrisdel101 commented on css/style.css
> +  width: 100%;
- This is too wide. Since the page is largely text it's awkward to read from edge to edge.
- The width of the styles currently works better.
- Standard I've always used is like a piece of paper, or a tablet size

2024-06-24 14:04 UTC, chrisdel101 commented on css/style.css
> +  padding-left: 8px !important;
- Never use important. I've been skunked a few times on this project by other ppl doing this.

2024-06-24 14:04 UTC, chrisdel101 commented on css/style.css
> +  border-color: #333 !important;
- Again, find a different way to do this. No important.

2024-06-24 14:04 UTC, chrisdel101 commented on css/dark-theme.css
> +  border-bottom: 1px solid #626262;
- just personal preference but I like the white border of the current styles more. I just think it pops more.

2024-06-24 14:04 UTC, chrisdel101 commented on css/dark-theme.css
> +  color: var(--dark_text) !important;
- Don't use important. Please find another way to make this work. You can make it more specific like `html.dark-mode #navbar ul#navmenu li a, html.dark-mode #navbar ul#navmenu li.dropit-trigger a` type of thing

2024-06-24 14:04 UTC, chrisdel101 commented on css/style.css
> +  font-weight: 200;
- This is too thick (I think). The current way it matches the Express icon more closely as well. 
- I like current way better.

2024-06-24 14:05 UTC, chrisdel101 commented
I think I needed to submit the review. Hopefully you can see them now.

2024-06-24 14:18 UTC, carlosstenzel commented on _includes/header/header-en.html
> +        <i class="fa fa-sun-o fa-lg hidden-light"></i>
I didn't find any other icon that could replace it :( 

https://fontawesome.com/v4/icons/

2024-06-24 14:50 UTC, carlosstenzel commented on _includes/header/header-en.html
> +        <i class="fa fa-sun-o fa-lg hidden-light"></i>
I added another icon for the sun
https://github.com/expressjs/expressjs.com/pull/1532

2024-06-24 14:51 UTC, carlosstenzel commented on _includes/header/header-en.html
> +        <i class="fa fa-sun-o fa-lg hidden-light"></i>
with fa icons
![Captura de Tela 2024-06-24 às 11 42 04](https://github.com/expressjs/expressjs.com/assets/3890516/cdd5f802-0541-45fe-adc4-5a5709c399fd)

new icon
![Captura de Tela 2024-06-24 às 11 45 51](https://github.com/expressjs/expressjs.com/assets/3890516/c7d39525-b24f-494f-bb10-939f7d9e7c66)

2024-11-26 01:33 UTC, closed without merging