Update database-integration.md
expressjs/expressjs.com pull request #1543
Opened 2024-07-19 13:45 UTC by selimsezr

add DuckDB integration

2024-07-19 19:31 UTC, crandmck requested changes

2024-07-19 19:31 UTC, crandmck commented on en/guide/database-integration.md
> +**Module**: [duckdb]([https://github.com/elastic/elasticsearch-js](https://github.com/duckdb/duckdb))
This is a malformed md link.  There are 2 URLs here--pick one.

2024-07-19 19:33 UTC, crandmck commented
@jonchurch I don't see any reason not to add DuckDB.  WDYT?

Separately--and in the spirit of reducing/eliminating links or endorsements of 3rd party packages or products--I wonder if we should either move this page to the "Advanced" menu or just remove it entirely?  Clearly, it has useful info, but...?

2024-07-20 10:43 UTC, selimsezr commented
It might be good to move it to the “Advanced” page. I tried for about 4 days to make the DuckDB connection with Nextjs and it didn't work. I did it much faster with Express. So I think it's important to write 3rd party applications. When there is an update or error, a PR/Issue can be created immediately.

I couldn't understand where the error was either, I only made changes in the .md file.

2024-07-22 16:42 UTC, crandmck commented
@selimsezr If you would address my comment about the link, we can consider merging this.

2024-08-25 20:39 UTC, crandmck commented
This hasn't been update for over a month, so closing.

2024-08-25 20:39 UTC, closed without merging