[WIP]: Update production best practices
expressjs/expressjs.com pull request #1679
Opened 2024-11-10 01:20 UTC by bjohansebas

Modernize this page by making the following changes:

- Update broken links
- Remove references to Upstart, as this service has been in maintenance mode for several years
- Remove references to Strongloop, updating documentation with current tools

2024-11-12 01:09 UTC, carlosstenzel approved these changes

2024-11-27 18:45 UTC, UlisesGascon reviewed
I like the changes, but I think that we need to have a good agreement on this (cc: @expressjs/express-tc )

2025-01-12 17:53 UTC, wesleytodd reviewed
I think this is an improvement for sure. Great work @bjohansebas!

I think we probably need to re-think the role our docs play in the ecosystem. Best practices have evolved quite a bit since this was all written, and it will evolve again in the coming years. We probably don't want to be the source for too much content like this unless we are able to keep it updated.

That said, for now, I am very much in support of improving this type of doc so LGTM!

2025-01-12 17:53 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
> +If you're logging app activity (for example, tracking traffic or API calls), instead of using `console.log()`, use a logging library like [Winston](https://www.npmjs.com/package/winston) or [Pino](ht
We should deprecate and remove all references to `winston` and `bunyan`. Pino is the only good recommendation these days.

2025-01-12 17:53 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
> +1.  All your asynchronous code must return promises (except emitters). If a particular library does not return promises, convert the base object by using a helper function like [util.promisify](https
This is pretty poorly worded imo, and frankly wrapping callback libraries in `util.promisify` is not best practice either. Additionally, since we added error handling support in v5 I wonder if we should remove or rewrite this section entirely?

2025-01-12 17:53 UTC, wesleytodd approved these changes
oops forgot to change it to `approve`

2025-01-13 08:52 UTC, UlisesGascon commented on en/advanced/best-practice-performance.md
> +1.  All your asynchronous code must return promises (except emitters). If a particular library does not return promises, convert the base object by using a helper function like [util.promisify](https
Agree... seems like we can focus on v5 and remove this section

2025-01-13 08:52 UTC, UlisesGascon commented on en/advanced/best-practice-performance.md
> +If you're logging app activity (for example, tracking traffic or API calls), instead of using `console.log()`, use a logging library like [Winston](https://www.npmjs.com/package/winston) or [Pino](ht
Agree too

2025-01-13 15:34 UTC, ctcpip requested changes
looks good.  we should remove the link to `forever` though

2025-01-13 15:34 UTC, ctcpip commented on en/advanced/best-practice-performance.md
>  * [Forever](https://www.npmjs.com/package/forever)
```suggestion
```

2025-01-13 15:41 UTC, ctcpip commented on en/advanced/best-practice-performance.md
>  For a feature-by-feature comparison of the three process managers, see [http://strong-pm.io/compare/](http://strong-pm.io/compare/).
```suggestion
```

2025-01-13 15:51 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +If you're logging app activity (for example, tracking traffic or API calls), instead of using `console.log()`, use a logging library like [Winston](https://www.npmjs.com/package/winston) or [Pino](ht
Should I also delete the blog post? I think it would be good to keep it.

2025-01-13 17:56 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +1.  All your asynchronous code must return promises (except emitters). If a particular library does not return promises, convert the base object by using a helper function like [util.promisify](https
I'll remove it, I'll open an issue to see if someone wants to make the change, or if not, I'll come back to it soon. I still need to think carefully about how to document it properly, and since my focus was on replacing links and updating some references in this PR, I don't want to delay it any further.

2025-02-10 00:32 UTC, bjohansebas commented
@expressjs/express-tc @expressjs/docs-wg could you review it again, please?

2025-02-13 23:08 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
>  app.get('/', (req, res, next) => {
```suggestion
app.get('/', async (req, res, next) => {
```

2025-02-13 23:32 UTC, jonchurch approved these changes

2025-02-14 15:20 UTC, Phillip9587 requested changes
Please check my comments.

Also the **Nginx** link in the _Cache request results_ section is not working and only redirecting to the main docs.

2025-02-14 15:20 UTC, Phillip9587 commented on en/advanced/best-practice-performance.md
>  Using any of these process managers will suffice to keep your application up, even if it does crash from time to time.
If you are only listing `pm2` you have to change the surrounding sentences to singular.

2025-02-14 15:20 UTC, Phillip9587 commented on en/advanced/best-practice-performance.md
> +Clustering is made possible with Node's [cluster module](https://nodejs.org/api/cluster.html). This enables a master process to spawn worker processes and distribute incoming connections among the wo
Should this both tools be recommended?

2025-02-14 15:20 UTC, Phillip9587 commented on en/advanced/best-practice-performance.md
> +Handing over tasks that do not require knowledge of application state to a reverse proxy frees up Express to perform specialized application tasks. For this reason, it is recommended to run Express b
```suggestion
Handing over tasks that do not require knowledge of application state to a reverse proxy frees up Express to perform specialized application tasks. For this reason, it is recommended to run Express behind a reverse proxy like [Nginx](https://www.nginx.org/) or [HAProxy](https://www.haproxy.org/) in production.
```

2025-02-14 15:40 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +Handing over tasks that do not require knowledge of application state to a reverse proxy frees up Express to perform specialized application tasks. For this reason, it is recommended to run Express b
good catch

2025-02-14 15:47 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +Clustering is made possible with Node's [cluster module](https://nodejs.org/api/cluster.html). This enables a master process to spawn worker processes and distribute incoming connections among the wo
I really didn't find any tools that could be recommended instead of those. We might want to remove them, although maybe at another pr

2025-02-14 15:49 UTC, wesleytodd reviewed
I am leaving this as a comment review because I am hesitant to make some of the new recommendations which are added here, but I don't want to block it.

2025-02-14 15:49 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
>  If you're logging for purposes of debugging, then instead of using `console.log()`, use a special debugging module like [debug](https://www.npmjs.com/package/debug). This module enables you to use th
I think we should remove this whole section. We should be recommending Pino for *all* logs, and recommend the `debug` log level for debugging. End applications using the `debug` package is even worse than libraries using it since the only thing it does well is avoid having to pass a logger instance around (which should not be a problem in app code like it is for many libraries).

2025-02-14 15:49 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
> +If you're logging app activity (for example, tracking traffic or API calls), instead of using `console.log()`, use a logging library like [Pino](https://www.npmjs.com/package/pino). There are more pa
I am not a big fan of this blog post. First it doens't mention the most critical thing about choosing a logging package: production performance overhead. Of which I am pretty certain `pino` is the only one with full feature support *and* [top perf](https://github.com/pinojs/pino/blob/main/docs/benchmarks.md).

2025-02-14 15:49 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
> +app.use((error, req, res, next) => {
I would prefer we not change the name here. `err` has been around as long as node, and there is so much example code out there with it that I think consistency (and in this case not changing what was there already) is good. This is a nitpick and not blocking the PR.

2025-02-14 15:49 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
>  Using any of these process managers will suffice to keep your application up, even if it does crash from time to time.
If we are only listing `pm2` I think we should make this section just a single line saying something to the point of:

```
Historically it was popular to use a node.js process manager like PM2, see their documentation if you wish to do this. Modern best practices have changed, and we now recommend using your system init for process management.
```

2025-02-14 15:49 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
> +Clustering is made possible with Node's [cluster module](https://nodejs.org/api/cluster.html). This enables a master process to spawn worker processes and distribute incoming connections among the wo
Hm, I have never used either of these packages for clustering. The first only has 4 downloads a week, which doens't mean it is a bad solution but for sure means it is not popular and might not be the best recommendation for us to make. The second seems more fully features, but I really don't see a reason to cluster with anything other than the core module.

2025-02-14 15:49 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
> +Clustering is made possible with Node's [cluster module](https://nodejs.org/api/cluster.html). This enables a master process to spawn worker processes and distribute incoming connections among the wo
I think I made this comment at the same time you did, I am fully in agreement with removing this.

2025-02-14 16:10 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +Clustering is made possible with Node's [cluster module](https://nodejs.org/api/cluster.html). This enables a master process to spawn worker processes and distribute incoming connections among the wo
Deleted

2025-02-14 16:11 UTC, dpopp07 reviewed
Just a quick proof read

2025-02-14 16:11 UTC, dpopp07 commented on en/advanced/best-practice-performance.md
> +Best practice is to handle errors as close to the site as possible. So while this is now handled in the router, it’s best to catch the error in the middleware and handle it without relying on separat
Minor typo:

```suggestion
Best practice is to handle errors as close to the site as possible. So while this is now handled in the router, it’s best to catch the error in the middleware and handle it without relying on separate error-handling middleware.
```

2025-02-14 16:11 UTC, dpopp07 commented on en/advanced/best-practice-performance.md
> +The next layer of reliability is to ensure that your app restarts when the server restarts. Systems can still go down for a variety of reasons. To ensure that your app restarts if the server crashes,
Minor typo:

```suggestion
The next layer of reliability is to ensure that your app restarts when the server restarts. Systems can still go down for a variety of reasons. To ensure that your app restarts if the server crashes, use the init system built into your OS. The main init system in use today is [systemd](https://wiki.debian.org/systemd).
```

2025-02-14 16:11 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
>  Using any of these process managers will suffice to keep your application up, even if it does crash from time to time.
changed

2025-02-14 16:11 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +If you're logging app activity (for example, tracking traffic or API calls), instead of using `console.log()`, use a logging library like [Pino](https://www.npmjs.com/package/pino). There are more pa
removed the blog

2025-02-14 16:12 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +app.use((error, req, res, next) => {
fixed

2025-02-14 16:17 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
>  If you're logging for purposes of debugging, then instead of using `console.log()`, use a special debugging module like [debug](https://www.npmjs.com/package/debug). This module enables you to use th
I think that's why the title of that section is 'Debugging' so for now, we can keep it.

2025-02-14 16:28 UTC, Phillip9587 commented
Please update the following link in the **Cache Request Results** section: https://www.nginx.com/resources/wiki/start/topics/examples/reverseproxycachingexample/ it is invalid and redirects to https://docs.nginx.com/

Maybe replace it with: https://blog.nginx.org/blog/nginx-caching-guide

2025-02-14 16:29 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
>  If you're logging for purposes of debugging, then instead of using `console.log()`, use a special debugging module like [debug](https://www.npmjs.com/package/debug). This module enables you to use th
Yeah, I agree that is the intent. I will not die on this hill, but I am strongly opinionated that the `debug` package is a worse outcome than using `pino`'s `debug` level logging. We can call this resolved despite my dislike of this recommendation though.

2025-02-14 16:30 UTC, wesleytodd commented
Looks like we have approvals and have resolved the concerns. The merge block now is just rebasing I think.

2025-02-14 16:34 UTC, bjohansebas commented
The only thing blocking this PR is @ctcpip 's request change. I can remove @ctcpip 's request change, but I would prefer that he remove it himself. I can wait a few more minutes.

2025-02-14 16:35 UTC, wesleytodd commented
Oh yeah, we should never remove others reviews. I saw a yellow "comment" review in the sidebar but missed that there was still a previous "change requested" review that was blocking and hidden in the collapsed comments.

2025-02-14 16:36 UTC, ctcpip requested changes

2025-02-14 16:36 UTC, ctcpip commented on en/advanced/best-practice-performance.md
> +Historically, it was popular to use a Node.js process manager like [PM2](https://github.com/Unitech/pm2). See their documentation if you wish to do this. However, modern best practices have changed,
I know this was suggested by @wesleytodd, but this seems... slightly heavy-handed (?), and at least could be worded better (`using your init system` vs `using your system's init`, for example.  Do we really want to take a position of saying using pm2 is not a "best practice"?  If that's the case (which I am challenging here), then we shouldn't even be mentioning pm2.

2025-02-14 16:39 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +Historically, it was popular to use a Node.js process manager like [PM2](https://github.com/Unitech/pm2). See their documentation if you wish to do this. However, modern best practices have changed,
That would require rewriting a large part where PM2 was mentioned, so removing it is not an option at the moment.

2025-02-14 16:41 UTC, ctcpip commented on en/advanced/best-practice-performance.md
>  If you're logging for purposes of debugging, then instead of using `console.log()`, use a special debugging module like [debug](https://www.npmjs.com/package/debug). This module enables you to use th
since we are not (already) changing this section, let's consider resolving that in a follow-on issue/PR.  the number of changes and revisions in this PR is already dragging

2025-02-14 16:42 UTC, ctcpip commented on en/advanced/best-practice-performance.md
>  If you're logging for purposes of debugging, then instead of using `console.log()`, use a special debugging module like [debug](https://www.npmjs.com/package/debug). This module enables you to use th
oh.. I see there is a strong recommendation below for `pino`, so .. maybe it should get updated because of that.  relaxing my stance here

2025-02-14 16:43 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
> +Historically, it was popular to use a Node.js process manager like [PM2](https://github.com/Unitech/pm2). See their documentation if you wish to do this. However, modern best practices have changed,
> Do we really want to take a position of saying using pm2 is not a "best practice"?

Clearly IMO yes lol, but I fully understand your reasoning for being hesitant. Having used basically all variants at different points of my career, I can comfortably say that operating system process management is *always* better. And even if you use `pm2` you nearly certainly have to also use your OS process manager to kick off `pm2`, so why make it more complicated?

> then we shouldn't even be mentioning pm2.

This is what I would prefer, but I thought that was a larger change from our existing docs.

> at least could be worded better (using your init system vs using your system's init, for example.

That's a good change, I didn't really spend a ton of time on that suggestion, my bad.

2025-02-14 16:46 UTC, ctcpip commented on en/advanced/best-practice-performance.md
>  #### What not to do
this is an existing issue with the doc, so we don't have to make this change here, but it's an easy one.

whenever you have a list of `DO`s and `DON'T DO`s, you want to list all the things you should do first, followed by the things to not do.  so this section should get moved so that it's the last within the `Handle exceptions properly` section

2025-02-14 16:46 UTC, ctcpip commented on en/advanced/best-practice-performance.md
> +The NODE_ENV environment variable specifies the environment in which an application is running (usually, development or production). One of the simplest things you can do to improve performance is to
```suggestion
The `NODE_ENV` environment variable specifies the environment in which an application is running (usually, development or production). One of the simplest things you can do to improve performance is to set `NODE_ENV` to `production`.
```

2025-02-14 16:48 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +Historically, it was popular to use a Node.js process manager like [PM2](https://github.com/Unitech/pm2). See their documentation if you wish to do this. However, modern best practices have changed,
I can dedicate another PR to removing PM2, but for now, I changed the wording to the suggestion that Chris proposed.

2025-02-14 16:51 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
>  #### What not to do
Done, and thanks for the suggestion, I didn't know that

2025-02-14 16:56 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
>  If you're logging for purposes of debugging, then instead of using `console.log()`, use a special debugging module like [debug](https://www.npmjs.com/package/debug). This module enables you to use th
I am on the fence and for sure would rather merge this as is than block it just because of this.

2025-02-14 16:56 UTC, wesleytodd commented on en/advanced/best-practice-performance.md
> +Historically, it was popular to use a Node.js process manager like [PM2](https://github.com/Unitech/pm2). See their documentation if you wish to do this. However, modern best practices have changed,
Sounds good to me.

2025-02-14 16:57 UTC, wesleytodd approved these changes
Changing to approved since we have a plan to address all the things I was concerned about in future PRs.

2025-02-14 16:59 UTC, Phillip9587 approved these changes

2025-02-14 17:01 UTC, bjohansebas commented on en/advanced/best-practice-performance.md
> +Historically, it was popular to use a Node.js process manager like [PM2](https://github.com/Unitech/pm2). See their documentation if you wish to do this. However, modern best practices have changed,
@ctcpip, do you consider this resolved?

2025-02-14 17:03 UTC, ctcpip commented on en/advanced/best-practice-performance.md
> +Historically, it was popular to use a Node.js process manager like [PM2](https://github.com/Unitech/pm2). See their documentation if you wish to do this. However, modern best practices have changed,
```suggestion
Historically, it was popular to use a Node.js process manager like [PM2](https://github.com/Unitech/pm2). See their documentation if you wish to do this. However, we recommend using your init system for process management.
```

2025-02-14 17:04 UTC, ctcpip approved these changes

2025-02-14 17:06 UTC, merged