feat: add language picker
expressjs/expressjs.com pull request #1695
Opened 2024-11-23 23:45 UTC by cengizcmataraci

Adding language picker to header
by [#1687 ](https://github.com/expressjs/expressjs.com/issues/1687)

2024-11-24 17:15 UTC, bjohansebas reviewed
Maybe we don't want it to be removed in mobile until it really breaks the mobile responsiveness.

With the selector, I think this part of the page can be removed now.
![image](https://github.com/user-attachments/assets/8cad3180-468d-421a-b3db-76eba3e7f14f)


I really love that this is being added.

2024-11-24 19:29 UTC, cengizcmataraci commented
I don't add the picker in the mobile, but I'll add it and remove the language part if you folks want. And I also like the picker. 😄

2024-11-26 00:20 UTC, carlosstenzel commented
@cengizcmataraci 
good job ;)

2024-12-22 12:52 UTC, cengizcmataraci commented
Hello, sorry about the delay. Could you review again, please? I added the language picker for mobile. I tested for various devices in browser dev tools. @bjohansebas @carlosstenzel

2024-12-23 11:07 UTC, carlosstenzel approved these changes

2025-01-06 18:24 UTC, bjohansebas commented on js/menu.js
> +			window.location.href = href;
Why is it necessary to do this?

2025-01-06 19:31 UTC, cengizcmataraci commented on js/menu.js
> +			window.location.href = href;
In this for loop, I am iterating over the languageItems elements, and if the clicked item’s href attribute exists, the page’s URL is updated accordingly. For example, if a user is on a German page and clicks the Turkish option, the page is directly redirected to the Turkish version.

2025-01-06 19:48 UTC, bjohansebas commented on js/menu.js
> +			window.location.href = href;
Yep, but wouldn't the href of the link do the same?

2025-01-07 18:44 UTC, cengizcmataraci commented on js/menu.js
> +			window.location.href = href;
Yes, you’re right, but in this case, I wouldn’t be able to handle the extra conditions above. I can change it if you’d like.

2025-01-07 22:24 UTC, bjohansebas commented on js/menu.js
> +			window.location.href = href;
I think this could indeed be removed, I’ve tested it and didn’t notice any strange behavior. Or, @cengizcmataraci did you encounter any unusual behavior while developing? If not, should this line be added?

2025-01-07 22:27 UTC, bjohansebas commented on _includes/language-picker-mobile.html
> +  <div id="language-picker-button" class="fa fa-language fa-2x button"></div>
I’d prefer to change this icon for one that looks more modern, maybe one from [Heroicons](https://heroicons.com/)? I could make the change tomorrow.

2025-01-12 16:53 UTC, cengizcmataraci commented on js/menu.js
> +			window.location.href = href;
No, you are correct. I will remove this line now, thank you.

2025-01-12 17:03 UTC, cengizcmataraci commented on _includes/language-picker-mobile.html
> +  <div id="language-picker-button" class="fa fa-language fa-2x button"></div>
Allright, could you check it again, please? @bjohansebas

2025-01-13 19:19 UTC, bjohansebas commented on _includes/language-picker-mobile.html
> +  <div id="language-picker-button" class="fa fa-language fa-2x button"></div>
Great, thanks for the change, it looks modern

2025-01-13 19:26 UTC, bjohansebas commented on js/menu.js
> +			window.location.href = href;
Okay, now it doesn't work when it's on mobile.

2025-01-13 19:48 UTC, bjohansebas commented
I will keep the icon for all screen sizes

2025-01-13 20:03 UTC, bjohansebas approved these changes
Thank you for working on this @cengizcmataraci, it really looks great

2025-01-13 20:35 UTC, ctcpip requested changes
don't the other footers need to be updated?

2025-01-13 20:35 UTC, ctcpip commented on _includes/footer/footer-en.html
> -    Documentation translations provided by StrongLoop/IBM:
we can't remove this

2025-01-13 20:35 UTC, ctcpip commented on _includes/footer/footer-id.html
> -  Dokumentasi versi terjemahan yang disediakan oleh StrongLoop/IBM:
we can't remove this

2025-01-13 20:39 UTC, bjohansebas commented on _includes/footer/footer-en.html
> -    Documentation translations provided by StrongLoop/IBM:
why?

2025-01-13 20:39 UTC, bjohansebas commented on _includes/footer/footer-id.html
> -  Dokumentasi versi terjemahan yang disediakan oleh StrongLoop/IBM:
why?

2025-01-13 21:14 UTC, ctcpip commented on _includes/footer/footer-en.html
> -    Documentation translations provided by StrongLoop/IBM:
They likely agreed to do the work and specifically asked that this attribution/credit appear there.

Some background [is here](https://github.com/expressjs/expressjs.com/issues/1166#issuecomment-664030084).

2025-01-13 21:15 UTC, ctcpip commented on _includes/footer/footer-id.html
> -  Dokumentasi versi terjemahan yang disediakan oleh StrongLoop/IBM:
https://github.com/expressjs/expressjs.com/pull/1695#discussion_r1913814532

2025-01-13 21:21 UTC, bjohansebas commented on _includes/footer/footer-en.html
> -    Documentation translations provided by StrongLoop/IBM:
Interesting context, so we will keep it.

2025-01-13 21:24 UTC, bjohansebas commented on _includes/footer/footer-en.html
> -    Documentation translations provided by StrongLoop/IBM:
The reason I was thinking of removing it, in case it serves as context in the future, was because the following banner was already displayed in each language.

![image](https://github.com/user-attachments/assets/2d48ad98-cf2b-4a29-9b71-9c1fd01e1653)

Which displayed their respective acknowledgment, where they translated it

2025-01-13 21:32 UTC, ctcpip commented on _includes/footer/footer-en.html
> -    Documentation translations provided by StrongLoop/IBM:
sure, but that only appears on the translated pages. the main documentation site in English would not display the attribution/credit

2025-01-13 21:42 UTC, bjohansebas commented on css/style.css
> +    display: flex !important;
We try not to use `!important`, please find a way to remove it.

2025-01-13 21:44 UTC, bjohansebas commented on _includes/footer/footer-en.html
> -    Documentation translations provided by StrongLoop/IBM:
@ctcpip Back added

2025-01-13 21:47 UTC, bjohansebas requested changes
Please remove the !important

2025-01-13 22:13 UTC, bjohansebas commented
On mobile, I think it would be better to handle it the same way as on desktop, meaning the menu doesn't take up the full width, similar to how Node.js does it

![image](https://github.com/user-attachments/assets/39c86421-fc00-4faf-ba06-3fd40f95d32b)

And maybe always keep the icon instead of showing the language name

2025-01-15 18:45 UTC, cengizcmataraci commented on css/style.css
> +    display: flex !important;
Sure, I will look at it.

2025-01-15 18:51 UTC, cengizcmataraci commented
> On mobile, I think it would be better to handle it the same way as on desktop, meaning the menu doesn't take up the full width, similar to how Node.js does it
> 
> ![image](https://private-user-images.githubusercontent.com/103585995/402716660-39c86421-fc00-4faf-ba06-3fd40f95d32b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NjY5NjcsIm5iZiI6MTczNjk2NjY2NywicGF0aCI6Ii8xMDM1ODU5OTUvNDAyNzE2NjYwLTM5Yzg2NDIxLWZjMDAtNGZhZi1iYTA2LTNmZDQwZjk1ZDMyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNVQxODQ0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzZmZDZjZGMzZDIyNmYzYWVjYTY3NGI2MmI5M2QyNTBmNTQxYWM4YmZkNDM5Y2MwMWY3MTIyZTdlMjE4MjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7z-sC0ut8JVVQGuyQCw7aqF1yzrbL3TVkejHAEpeJCg)
> 
> And maybe always keep the icon instead of showing the language name

Are you referring to the desktop version? Because we don’t display the language name in the mobile picker. And do we really think the Node.js website offers a better UX for the mobile picker? I find it a bit confusing. In our design, the user opens the picker solely to change the language, and once that’s done, it closes automatically. @bjohansebas

2025-01-15 19:32 UTC, bjohansebas commented
I'm not an expert in UX/UI to determine if Node.js has the best mobile user experience, it was just a suggestion, so I'm okay with leaving it as it is, which I also think is great.

2025-01-16 11:21 UTC, carlosstenzel commented
In my analysis, I believe it is good for this first version.

![Captura de tela 2025-01-16 081427](https://github.com/user-attachments/assets/bf8d6fb0-4e6b-488b-9a9f-3b12333db3a8)
![Captura de tela 2025-01-16 081804](https://github.com/user-attachments/assets/4f6ca6fd-8fae-4199-9a26-ac8015f95b86)

2025-01-20 09:53 UTC, cengizcmataraci commented
Okay, I removed the important. Could you review again, please? @bjohansebas @carlosstenzel

2025-01-20 17:42 UTC, bjohansebas approved these changes
LGTM

2025-02-04 19:17 UTC, ctcpip approved these changes

2025-02-04 19:46 UTC, dpopp07 commented on css/style.css
> +  margin-right: -10px;
This block is missing indentation:

```suggestion
    display: flex;
    align-items: center;
    gap: 8px;
    margin-right: -10px;
```

2025-02-04 19:49 UTC, bjohansebas commented on css/style.css
> +  margin-right: -10px;
That doesn't really matter much, we need to fix the styling issue at some point to make it uniform, you can check https://github.com/expressjs/expressjs.com/issues/1596.

2025-02-04 19:53 UTC, dpopp07 commented on css/style.css
> +  margin-right: -10px;
Agreed. Still, it felt worth noting as the rest of the PR was internally consistent.

2025-02-04 22:16 UTC, bjohansebas commented on css/style.css
> +  margin-right: -10px;
fixed, thanks @dpopp07

2025-02-04 22:17 UTC, bjohansebas approved these changes

2025-02-04 22:19 UTC, merged

2025-02-04 22:19 UTC, bjohansebas commented
awesome work @cengizcmataraci,