fix: fix menu text align
expressjs/expressjs.com pull request #1699
Opened 2024-11-25 02:06 UTC by bjohansebas

Fix a bug that was accidentally introduced in #1670

before:
![image](https://github.com/user-attachments/assets/a42a6a88-7b70-4e1a-ae52-7fe7ffa3c805)

after:
![image](https://github.com/user-attachments/assets/8468145f-59ac-4cc1-856e-8c29ac52e937)

2024-11-25 14:32 UTC, chrisdel101 commented
I like the new way with the links centered, better than original left-positioned. But it's buggy. 
Any chance of just fixing up this method? I saw this in the PR and liked it, but missed the bugginess. 
![Screenshot 2024-11-25 083032](https://github.com/user-attachments/assets/d7dd572b-b2d5-4c9f-a48d-b12c50e14461)

2024-11-26 17:46 UTC, bjohansebas commented
I also liked that it was centered, so I’m going to center the menu.

2024-11-27 00:43 UTC, carlosstenzel approved these changes

2025-01-13 20:00 UTC, bjohansebas commented
I need approval with write permissions cc @expressjs/express-tc

2025-01-13 20:21 UTC, ctcpip commented
we should not be centering text as this is bad for [a11y](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-visual-presentation)

2025-01-13 20:28 UTC, ctcpip requested changes
.

2025-01-13 20:36 UTC, bjohansebas commented
@chrisdel101 The link you provided does not mention anything about centering the text, only about justifying the text, which is indeed a bad practice in terms of accessibility.

2025-01-13 20:43 UTC, ctcpip commented
in that context, centered is included. these are well-established accessibility guideliens

https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Supplemental_Guidance:_Text_Justification

2025-01-13 20:46 UTC, ctcpip commented
clear usability issue here

![Screenshot 2025-01-13 at 2 44 58 PM](https://github.com/user-attachments/assets/2b891f34-2b2e-4c39-a800-64d3df5a5128)

2025-01-13 20:47 UTC, bjohansebas commented
Okay, thanks for the resource, I will remove it

2025-01-13 20:55 UTC, ctcpip commented on css/style.css
>    }
```suggestion
```

2025-01-13 20:55 UTC, ctcpip requested changes
left pane should not have centered text

2025-01-13 20:59 UTC, bjohansebas commented on css/style.css
>    }
😞 
![image](https://github.com/user-attachments/assets/53120839-13e7-4b84-8a06-5dacae11f7cb)

2025-01-13 21:04 UTC, bjohansebas commented on css/style.css
>    }
fixed

2025-01-13 21:07 UTC, ctcpip requested changes
this is the wrong change...

2025-01-13 21:08 UTC, ctcpip commented on css/style.css
>    }
you changed the wrong CSS selector/rule

2025-01-13 21:16 UTC, bjohansebas commented
Nothing will be centered anymore if #1732 is merged

2025-01-13 21:18 UTC, ctcpip commented
@bjohansebas that's... not true at all

edit: I'm not sure what you meant, but the layout will still be centered as done in https://github.com/expressjs/expressjs.com/issues/1668

2025-01-13 21:28 UTC, ctcpip approved these changes

2025-01-13 21:29 UTC, merged