Feat/adjust in home poc
expressjs/expressjs.com pull request #1706
Opened 2024-12-04 12:46 UTC by carlosstenzel

Testing changes to the structure of the home page

Before:
![Captura de Tela 2024-12-04 às 09 44 53](https://github.com/user-attachments/assets/479f34b7-f0c7-48d6-b6fd-9107eac00593)

After:
![Captura de Tela 2024-12-04 às 09 45 15](https://github.com/user-attachments/assets/3fb5c009-d0cb-400b-ac17-2478c1ac1608)

** I made the changes only in the pt-br language just to illustrate

LINK PREVIEW IN PT-BR https://deploy-preview-1706--expressjscom-preview.netlify.app/pt-br/

2024-12-05 02:08 UTC, bjohansebas commented
I like it, I don't think we should add the quick example title.

2024-12-05 02:10 UTC, bjohansebas commented on pt-br/index.md
> +          <a href="{{ page.lang }}/guide/using-middleware.html" class="learn-more">Saiba mais →</a>
There was always this 404, it's time to fix it.
```suggestion
          <a href="/{{ page.lang }}/guide/using-middleware.html" class="learn-more">Saiba mais →</a>
```

2024-12-05 02:11 UTC, bjohansebas commented on pt-br/index.md
> +const express = require('express')
Maybe it's time to promote ESM?

cc: @expressjs/express-tc

2024-12-20 16:09 UTC, UlisesGascon reviewed
This looks promising! Great work @carlosstenzel! :heart:

2025-01-08 22:49 UTC, wesleytodd approved these changes
Agreed with @bjohansebas on not needing the title, but other than that I like it a lot!

2025-01-09 00:45 UTC, carlosstenzel commented
@bjohansebas @UlisesGascon @wesleytodd  

I made some modifications to leave a smaller change to be implemented in small steps, could you review it again?

2025-01-09 17:56 UTC, bjohansebas approved these changes
It looks great

2025-01-09 18:23 UTC, bjohansebas requested changes

2025-01-09 18:23 UTC, bjohansebas commented on pt-br/index.md
> -</section>
This should not be removed

2025-01-10 17:12 UTC, bjohansebas approved these changes

2025-01-10 17:14 UTC, merged