CLI rename
expressjs/expressjs.com pull request #720
Opened 2016-10-06 11:11 UTC by davidgatti

Change the command to generate the structure to the one that actually works.

2016-10-06 17:14 UTC, crandmck commented
Thanks for the PR.  

Not to make a mountain out of a molehill, but the problem is that the package name is `express-generator` and the command is `express`, so one could argue that either of the following is correct:
- "Install `express-generator` with the following command ..." (what we have now) 
- "Install `express`  with the following command ..." (what you propose)

To anyone familiar with Express, it's not confusing, but it could potentially be confusing to a newcomer.

Perhaps it would be most clear to say:

"The `express-generator` package installs the `express` command-line tool; install it by entering this command:
```$ npm install express-generator -g```

(Instead of "installs the `express` command-line tool" could also say "sets up..." or "creates..." to distinguish from an npm install).

Thoughts?

2016-10-07 00:06 UTC, dougwilson requested changes

2016-10-07 00:06 UTC, dougwilson commented on en/starter/generator.md
> +Install `express` with the following command:
> Install `express` with the following command

Yes, definitely very poor wording here. It sounds like you're _installing express_, which to me, sounds like this module express. I understand that there are people (like me), who would think `express` means the module and other (yourself) who would think `express` means the command line program.

I'm not saying either is right or wrong, but as you can see, with both thinking those different things, I think it means the entire wording just needs to be completely redone to make the intent clear.

2016-10-07 00:11 UTC, crandmck commented on en/starter/generator.md
> +Install `express` with the following command:
@dougwilson What do you think of my suggestion above?

2016-10-07 00:13 UTC, dougwilson commented on en/starter/generator.md
> +Install `express` with the following command:
Seems fine.

2016-10-07 08:25 UTC, davidgatti commented
OK guys, check the following change. And let me know how you like it :)

2016-10-07 16:13 UTC, crandmck commented
Thanks @davidgatti this is close, but the wording is not quite right: "... with the following example" should be "... with the following command".

Also, I think it's helpful to preface the statement with something like this to clarify what's actually going on:

"The `express-generator` package installs the `express` command-line tool"

2016-10-11 17:25 UTC, davidgatti commented
What do you think now? :)

2016-10-11 18:02 UTC, crandmck commented
Works for me.  Thanks @davidgatti

2016-10-11 18:02 UTC, merged