Fix the formatting of the 'formatting' section
expressjs/expressjs.com pull request #872
Opened 2017-10-25 10:39 UTC by shawwn

Closes #871.

2017-10-25 18:32 UTC, crandmck requested changes
Thanks for the PR.  I like your suggestion, but I think it would be even better if you added a code block showing the result, e.g. 

The result looks like this:

```js
var express = require('express')
var app = express()
app.listen(3000)
```

2017-10-25 18:32 UTC, crandmck commented on README.md
>  The default GitHub Pages syntax highlighting has been disabled in `_config.yml to allow highlighting with prism.js.
As long as you're at it, could you please fix this unrelated issue --- add the terminating backtick... s/be `_config.yml` .. thx!

2017-11-03 21:09 UTC, crandmck commented
I made these changes with 633ae4e238514025b85537532bfea8305d54d3ce

Thanks for raising the issue @shawwn

2017-11-03 21:09 UTC, closed without merging

2017-11-04 00:23 UTC, shawwn commented
I kind of wanted to be listed as a contributor to the repo. :) Oh well.

I didn't understand your reply. Sorry about that. I see now what you were asking for.

2017-11-06 19:33 UTC, crandmck commented
No worries, @shawwn 
I'd be happy to accept other contributions from you, if you find anything else that needs fixing.  Then you could be a contributor. :-)