Added example for using mongodb package v3.*
expressjs/expressjs.com pull request #927
Opened 2018-04-15 20:07 UTC by vegemite4me

The existing example for Mongo DB assumes the user is using v2.* of the mongodb package. v3.* is slightly different.

2018-05-22 03:22 UTC, crandmck requested changes
One typo, otherwise looks OK to me.

2018-05-22 03:22 UTC, crandmck commented on en/guide/database-integration.md
> +  var db = client.db('animals)
missing closing quote here.

2018-05-22 18:46 UTC, vegemite4me commented
Good spot. I think I've made the correction, but please check.

2018-05-23 01:51 UTC, crandmck commented
Looks good, thanks!

2018-05-23 01:51 UTC, merged