Update hello-world.md
expressjs/expressjs.com pull request #963
Opened 2018-08-08 22:04 UTC by adescode

2018-08-08 22:08 UTC, dougwilson requested changes

2018-08-08 22:08 UTC, dougwilson commented on en/starter/hello-world.md
> +app.listen(port, host, () => console.log('Example app listening on port 3000!'))
There is no host nor port variable in the code, which would render this inoperable.

2018-08-14 20:45 UTC, crandmck commented
@adescode I'm confused about the purpose of this PR.  I see  your initial commit was a change to a single line in the "Hello World" example, and Doug commented on it.  But your second commit was to delete the entire file.  We need to keep the file, but if you have suggested changes, I'm certainly open to discussing and/or reviewing them.

2018-09-16 03:23 UTC, dougwilson commented
Closed due to issue and no response.

2018-09-16 03:23 UTC, closed without merging